from sqlalchemy import Column, Integer, String, DateTime, Text, JSON, Boolean
from sqlalchemy.sql import func
from backend.database import Base


class Report(Base):
    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, autoincrement=True)
    datasource_id = Column(Integer, nullable=False)
    title = Column(String(200), nullable=False)
    report_type = Column(String(50), default="comprehensive")  # comprehensive, performance, security
    status = Column(String(20), default="generating")  # generating, completed, failed
    summary = Column(Text, nullable=True)
    content_md = Column(Text, nullable=True)
    content_html = Column(Text, nullable=True)
    findings = Column(JSON, nullable=True)
    created_at = Column(DateTime, server_default=func.now())
    completed_at = Column(DateTime, nullable=True)

    # AI-related columns
    ai_analysis = Column(Text, nullable=True)  # Full AI conversation text
    ai_model_id = Column(Integer, nullable=True)  # Which AI model was used
    kb_ids = Column(JSON, nullable=True)  # Knowledge bases used during analysis
    generation_method = Column(String(20), default="rule-based")  # "ai" or "rule-based"
    error_message = Column(Text, nullable=True)  # Error details if generation failed

    # Scheduled report columns
    is_scheduled = Column(Boolean, default=False)  # True if generated by scheduler
    schedule_config_id = Column(Integer, nullable=True)
    retention_days = Column(Integer, default=30)  # Days to keep scheduled reports

    # Inspection trigger columns
    trigger_type = Column(String(20), nullable=True)  # 'scheduled', 'manual', 'anomaly'
    trigger_id = Column(Integer, nullable=True)
    trigger_reason = Column(String(500), nullable=True)  # e.g., "CPU 95% > 80% for 60s"

    # AI inspection columns
    skill_executions = Column(JSON, nullable=True)  # Audit trail of skills called
    ai_conversation_id = Column(Integer, nullable=True)  # Link to diagnostic_session
